require 'dotenv'
Dotenv.load

lane :test do
  appcircle_testing_distribution(
    personalAPIToken: ENV["AC_PERSONAL_API_TOKEN"],
    appPath: ENV["AC_APP_PATH"],
    profileName: ENV["AC_PROFILE_NAME"],
    createProfileIfNotExists: ENV["CREATE_PROFILE_IF_NOT_EXISTS"] == "true",
    message: ENV["AC_MESSAGE"],
  )
end
