lane :test do
  appcircle_testing_distribution(
    accessToken: ENV["AC_ACCESS_TOKEN"],
    profileName: ENV["AC_PROFILE_NAME"],
    appPath: ENV["AC_APP_PATH"],
    message: ENV["AC_MESSAGE"],
    createProfileIfNotExists: true
  )
end
